const toggle = [
  "<template>",
  "  <label",
  "    class=\"nx-toggle\"",
  "    :class=\"[classes, { 'nx-toggle--on': isOn, 'nx-toggle--disabled': disabled }]\"",
  "    :style=\"style\"",
  "  >",
  "    <button",
  "      class=\"nx-toggle__track\"",
  "      type=\"button\"",
  "      role=\"switch\"",
  "      :aria-checked=\"isOn ? 'true' : 'false'\"",
  "      :aria-label=\"label || 'Toggle'\"",
  "      :disabled=\"disabled\"",
  "      @click=\"toggle\"",
  "    >",
  "      <span class=\"nx-toggle__knob\">",
  "        <NxIcon v-if=\"isOn && onIcon\" :name=\"onIcon\" :size=\"knobGlyph\" />",
  "        <NxIcon v-else-if=\"!isOn && offIcon\" :name=\"offIcon\" :size=\"knobGlyph\" />",
  "      </span>",
  "    </button>",
  "",
  "    <span v-if=\"label || hint || onLabel || offLabel\" class=\"nx-toggle__body\">",
  "      <span class=\"nx-toggle__label\">{{ label }}</span>",
  "      <span v-if=\"stateText\" class=\"nx-toggle__hint\">{{ stateText }}</span>",
  "    </span>",
  "  </label>",
  "</template>",
  "",
  "<script setup>",
  "import { computed } from \"vue\";",
  "import NxIcon from \"./NxIcon.vue\";",
  "import { useBox, useVisuals } from \"@/composables/useVisuals\";",
  "import { visualProps } from \"@/config/visualProps\";",
  "",
  "const SIZE_SCALE = {",
  "  xs: { width: 30, height: 16, knob: 10 },",
  "  sm: { width: 36, height: 20, knob: 14 },",
  "  md: { width: 46, height: 24, knob: 18 },",
  "  lg: { width: 56, height: 28, knob: 22 },",
  "  xl: { width: 66, height: 34, knob: 26 },",
  "};",
  "",
  "const props = defineProps({",
  "  ...visualProps,",
  "  modelValue: { type: Boolean, default: false },",
  "  label: { type: String, default: \"\" },",
  "  hint: { type: String, default: \"\" },",
  "  onLabel: { type: String, default: \"\" },",
  "  offLabel: { type: String, default: \"\" },",
  "  onIcon: { type: String, default: \"\" },",
  "  offIcon: { type: String, default: \"\" },",
  "  knobShape: { type: String, default: \"round\" },",
  "  disabled: { type: Boolean, default: false },",
  "});",
  "",
  "const emit = defineEmits([\"update:modelValue\", \"change\"]);",
  "",
  "const { vars, classes } = useVisuals(props, {",
  "  base: {",
  "    bg: \"var(--nx-surface-3)\",",
  "    fg: \"var(--nx-ink)\",",
  "    border: \"var(--nx-ink)\",",
  "    accent: \"var(--nx-accent)\",",
  "  },",
  "});",
  "",
  "const box = useBox(props);",
  "",
  "const scale = computed(() => SIZE_SCALE[props.size] || SIZE_SCALE.md);",
  "const isOn = computed(() => Boolean(props.modelValue));",
  "const knobGlyph = computed(() => Math.round(scale.value.knob * 0.72));",
  "",
  "const stateText = computed(() => {",
  "  if (isOn.value) return props.onLabel || props.hint;",
  "  return props.offLabel || props.hint;",
  "});",
  "",
  "const style = computed(() => ({",
  "  ...vars.value,",
  "  ...box.value,",
  "  \"--c-sw-w\": `${scale.value.width}px`,",
  "  \"--c-sw-h\": `${scale.value.height}px`,",
  "  \"--c-sw-knob\": `${scale.value.knob}px`,",
  "  \"--c-knob-radius\": props.knobShape === \"square\" ? \"0px\" : \"999px\",",
  "}));",
  "",
  "function toggle() {",
  "  if (props.disabled) return;",
  "  emit(\"update:modelValue\", !isOn.value);",
  "  emit(\"change\", !isOn.value);",
  "}",
  "</script>",
  "",
  "<style scoped>",
  ".nx-toggle {",
  "  display: inline-flex;",
  "  align-items: center;",
  "  gap: var(--nx-ctl-gap);",
  "  color: var(--c-fg);",
  "  cursor: pointer;",
  "}",
  "",
  ".nx-toggle__track {",
  "  position: relative;",
  "  flex: none;",
  "  width: var(--c-sw-w);",
  "  height: var(--c-sw-h);",
  "  padding: 2px;",
  "  background-color: var(--c-bg);",
  "  border: var(--c-bd-w, var(--nx-ctl-border)) var(--c-bd-style, solid) var(--c-bd);",
  "  border-radius: var(--c-radius, 999px);",
  "  cursor: pointer;",
  "  transition: background-color var(--nx-dur) var(--nx-ease);",
  "  filter: var(--c-filter);",
  "  box-shadow: var(--c-shadow);",
  "  transform: var(--c-transform);",
  "  opacity: var(--c-opacity);",
  "}",
  "",
  ".nx-toggle--on .nx-toggle__track {",
  "  background-color: var(--c-accent);",
  "}",
  "",
  ".nx-toggle__knob {",
  "  position: absolute;",
  "  top: 2px;",
  "  left: 2px;",
  "  display: grid;",
  "  place-items: center;",
  "  width: var(--c-sw-knob);",
  "  height: var(--c-sw-knob);",
  "  color: var(--c-fg);",
  "  background: var(--c-knob-bg, var(--nx-surface-2));",
  "  border: 2px solid var(--c-bd);",
  "  border-radius: var(--c-knob-radius);",
  "  transition: translate var(--nx-dur) var(--nx-ease-bounce);",
  "}",
  "",
  ".nx-toggle--on .nx-toggle__knob {",
  "  translate: calc(var(--c-sw-w) - var(--c-sw-knob) - 8px) 0;",
  "}",
  "",
  ".nx-toggle__body {",
  "  display: flex;",
  "  flex-direction: column;",
  "  gap: 2px;",
  "  min-width: 0;",
  "}",
  "",
  ".nx-toggle__label {",
  "  font-size: var(--c-font-size, var(--nx-ctl-font));",
  "  font-weight: var(--c-weight, 600);",
  "  line-height: 1.35;",
  "}",
  "",
  ".nx-toggle__hint {",
  "  font-size: var(--nx-fs-xs);",
  "  color: var(--c-muted);",
  "}",
  "",
  ".nx-toggle--disabled {",
  "  opacity: 0.55;",
  "  cursor: not-allowed;",
  "}",
  "",
  ".nx-toggle--disabled .nx-toggle__track {",
  "  cursor: not-allowed;",
  "}",
  "</style>",
  "",
].join("\n");

const slider = [
  "<template>",
  "  <div class=\"nx-slider\" :class=\"classes\" :style=\"style\">",
  "    <div v-if=\"label || showValue\" class=\"nx-slider__meta\">",
  "      <span class=\"nx-slider__label\">{{ label }}</span>",
  "      <span v-if=\"showValue\" class=\"nx-slider__value\">{{ displayValue }}</span>",
  "    </div>",
  "",
  "    <input",
  "      class=\"nx-slider__input\"",
  "      type=\"range\"",
  "      :min=\"min\"",
  "      :max=\"max\"",
  "      :step=\"step\"",
  "      :value=\"modelValue\"",
  "      :disabled=\"disabled\"",
  "      :style=\"trackStyle\"",
  "      @input=\"onInput\"",
  "    />",
  "",
  "    <div v-if=\"marks\" class=\"nx-slider__marks\">",
  "      <span>{{ min }}{{ unit }}</span>",
  "      <span>{{ mid }}{{ unit }}</span>",
  "      <span>{{ max }}{{ unit }}</span>",
  "    </div>",
  "  </div>",
  "</template>",
  "",
  "<script setup>",
  "import { computed } from \"vue\";",
  "import { useBox, useVisuals } from \"@/composables/useVisuals\";",
  "import { visualProps } from \"@/config/visualProps\";",
  "",
  "const props = defineProps({",
  "  ...visualProps,",
  "  modelValue: { type: Number, default: 50 },",
  "  min: { type: Number, default: 0 },",
  "  max: { type: Number, default: 100 },",
  "  step: { type: Number, default: 1 },",
  "  label: { type: String, default: \"\" },",
  "  unit: { type: String, default: \"\" },",
  "  showValue: { type: Boolean, default: true },",
  "  marks: { type: Boolean, default: false },",
  "  disabled: { type: Boolean, default: false },",
  "});",
  "",
  "const emit = defineEmits([\"update:modelValue\", \"change\"]);",
  "",
  "const { vars, classes } = useVisuals(props, {",
  "  base: {",
  "    bg: \"transparent\",",
  "    fg: \"var(--nx-ink)\",",
  "    border: \"var(--nx-ink)\",",
  "    accent: \"var(--nx-accent)\",",
  "  },",
  "});",
  "",
  "const box = useBox(props);",
  "",
  "const percent = computed(() => {",
  "  const span = props.max - props.min;",
  "  if (span <= 0) return 0;",
  "  return Math.min(Math.max(((props.modelValue - props.min) / span) * 100, 0), 100);",
  "});",
  "",
  "const mid = computed(() => Math.round((props.min + props.max) / 2));",
  "const displayValue = computed(() => `${props.modelValue}${props.unit}`);",
  "",
  "const trackStyle = computed(() => ({",
  "  background: `linear-gradient(90deg, ${vars.value[\"--c-accent\"]} 0%, ${vars.value[\"--c-accent\"]} ${percent.value}%, ${vars.value[\"--c-muted\"]} ${percent.value}%, ${vars.value[\"--c-muted\"]} 100%)`,",
  "}));",
  "",
  "const style = computed(() => ({ ...vars.value, ...box.value }));",
  "",
  "function onInput(event) {",
  "  emit(\"update:modelValue\", Number(event.target.value));",
  "  emit(\"change\", Number(event.target.value));",
  "}",
  "</script>",
  "",
  "<style scoped>",
  ".nx-slider {",
  "  display: flex;",
  "  flex-direction: column;",
  "  gap: 6px;",
  "  color: var(--c-fg);",
  "}",
  "",
  ".nx-slider__meta {",
  "  display: flex;",
  "  align-items: baseline;",
  "  justify-content: space-between;",
  "  gap: var(--nx-sp-3);",
  "}",
  "",
  ".nx-slider__label {",
  "  font-size: var(--nx-fs-xs);",
  "  font-weight: 800;",
  "  text-transform: uppercase;",
  "  letter-spacing: 0.07em;",
  "}",
  "",
  ".nx-slider__value {",
  "  font-family: var(--nx-font-mono);",
  "  font-size: var(--nx-fs-xs);",
  "  padding: 1px 6px;",
  "  border: 2px solid var(--c-bd);",
  "  background: var(--nx-surface-2);",
  "  color: var(--nx-ink);",
  "}",
  "",
  ".nx-slider__input {",
  "  width: 100%;",
  "  height: calc(var(--nx-ctl-pad-y) + 10px);",
  "  margin: 0;",
  "  appearance: none;",
  "  background-color: var(--nx-surface-3);",
  "  border: var(--c-bd-w, var(--nx-ctl-border)) solid var(--c-bd);",
  "  border-radius: var(--c-radius, 0);",
  "  cursor: pointer;",
  "  outline: none;",
  "  filter: var(--c-filter);",
  "  box-shadow: var(--c-shadow);",
  "}",
  "",
  ".nx-slider__input::-webkit-slider-thumb {",
  "  appearance: none;",
  "  width: calc(var(--nx-ctl-pad-y) + 12px);",
  "  height: calc(var(--nx-ctl-pad-y) + 12px);",
  "  background: var(--nx-surface-2);",
  "  border: 3px solid var(--c-bd);",
  "  border-radius: var(--c-radius, 0);",
  "  cursor: grab;",
  "}",
  "",
  ".nx-slider__input::-moz-range-thumb {",
  "  width: calc(var(--nx-ctl-pad-y) + 12px);",
  "  height: calc(var(--nx-ctl-pad-y) + 12px);",
  "  background: var(--nx-surface-2);",
  "  border: 3px solid var(--c-bd);",
  "  border-radius: var(--c-radius, 0);",
  "  cursor: grab;",
  "}",
  "",
  ".nx-slider__input:disabled {",
  "  opacity: 0.55;",
  "  cursor: not-allowed;",
  "}",
  "",
  ".nx-slider__marks {",
  "  display: flex;",
  "  justify-content: space-between;",
  "  font-family: var(--nx-font-mono);",
  "  font-size: var(--nx-fs-2xs);",
  "  color: var(--c-muted);",
  "}",
  "</style>",
  "",
].join("\n");

const progress = [
  "<template>",
  "  <div class=\"nx-progress\" :class=\"classes\" :style=\"style\">",
  "    <div v-if=\"label || showValue\" class=\"nx-progress__meta\">",
  "      <span class=\"nx-progress__label\">{{ label }}</span>",
  "      <span v-if=\"showValue\" class=\"nx-progress__value\">",
  "        {{ indeterminate ? statusText : percentLabel }}",
  "      </span>",
  "    </div>",
  "",
  "    <div class=\"nx-progress__track\" :class=\"{ 'nx-progress__track--striped': striped }\">",
  "      <div",
  "        class=\"nx-progress__bar\"",
  "        :class=\"{ 'nx-progress__bar--indeterminate': indeterminate }\"",
  "        :style=\"barStyle\"",
  "      />",
  "      <span v-for=\"notch in notches\" :key=\"notch\" class=\"nx-progress__notch\" :style=\"{ left: notch + '%' }\" />",
  "    </div>",
  "",
  "    <div v-if=\"marks\" class=\"nx-progress__marks\">",
  "      <span>0{{ unit }}</span>",
  "      <span>{{ max }}{{ unit }}</span>",
  "    </div>",
  "  </div>",
  "</template>",
  "",
  "<script setup>",
  "import { computed } from \"vue\";",
  "import { useBox, useVisuals } from \"@/composables/useVisuals\";",
  "import { visualProps } from \"@/config/visualProps\";",
  "",
  "const props = defineProps({",
  "  ...visualProps,",
  "  value: { type: Number, default: 40 },",
  "  max: { type: Number, default: 100 },",
  "  label: { type: String, default: \"\" },",
  "  unit: { type: String, default: \"%\" },",
  "  statusText: { type: String, default: \"Working\" },",
  "  showValue: { type: Boolean, default: true },",
  "  striped: { type: Boolean, default: false },",
  "  indeterminate: { type: Boolean, default: false },",
  "  ticks: { type: Number, default: 0 },",
  "  marks: { type: Boolean, default: false },",
  "});",
  "",
  "const { vars, classes } = useVisuals(props, {",
  "  base: {",
  "    bg: \"var(--nx-surface-3)\",",
  "    fg: \"var(--nx-ink)\",",
  "    border: \"var(--nx-ink)\",",
  "    accent: \"var(--nx-accent)\",",
  "  },",
  "});",
  "",
  "const box = useBox(props);",
  "",
  "const clamped = computed(() => Math.min(Math.max(props.value, 0), props.max));",
  "const ratio = computed(() => (props.max > 0 ? clamped.value / props.max : 0));",
  "const percentLabel = computed(() => `${Math.round(ratio.value * 100)}${props.unit}`);",
  "",
  "const notches = computed(() => {",
  "  const count = Math.max(0, Math.floor(props.ticks));",
  "  if (!count) return [];",
  "  return Array.from({ length: count }, (unused, index) => ((index + 1) * 100) / (count + 1));",
  "});",
  "",
  "const barStyle = computed(() => ({",
  "  width: props.indeterminate ? \"38%\" : `${ratio.value * 100}%`,",
  "}));",
  "",
  "const style = computed(() => ({",
  "  ...vars.value,",
  "  ...box.value,",
  "  \"--c-bar\": props.indeterminate ? \"var(--c-accent)\" : \"var(--c-accent)\",",
  "}));",
  "</script>",
  "",
  "<style scoped>",
  ".nx-progress {",
  "  display: flex;",
  "  flex-direction: column;",
  "  gap: 6px;",
  "  color: var(--c-fg);",
  "}",
  "",
  ".nx-progress__meta {",
  "  display: flex;",
  "  align-items: baseline;",
  "  justify-content: space-between;",
  "  gap: var(--nx-sp-3);",
  "}",
  "",
  ".nx-progress__label {",
  "  font-size: var(--nx-fs-xs);",
  "  font-weight: 800;",
  "  text-transform: uppercase;",
  "  letter-spacing: 0.07em;",
  "}",
  "",
  ".nx-progress__value {",
  "  font-family: var(--nx-font-mono);",
  "  font-size: var(--nx-fs-2xs);",
  "}",
  "",
  ".nx-progress__track {",
  "  position: relative;",
  "  display: flex;",
  "  align-items: stretch;",
  "  height: var(--c-height, calc(var(--nx-ctl-pad-y) * 1.6));",
  "  overflow: hidden;",
  "  background-color: var(--c-bg);",
  "  border: var(--c-bd-w, var(--nx-ctl-border)) var(--c-bd-style, solid) var(--c-bd);",
  "  border-radius: var(--c-radius, var(--nx-ctl-radius));",
  "  filter: var(--c-filter);",
  "  box-shadow: var(--c-shadow);",
  "  transform: var(--c-transform);",
  "  opacity: var(--c-opacity);",
  "}",
  "",
  ".nx-progress__track--striped {",
  "  background-image: repeating-linear-gradient(",
  "    45deg,",
  "    var(--nx-grid-line) 0 6px,",
  "    transparent 6px 12px",
  "  );",
  "}",
  "",
  ".nx-progress__bar {",
  "  height: 100%;",
  "  min-width: 0;",
  "  background-color: var(--c-bar);",
  "  border-right: 2px solid var(--c-bd);",
  "  transition: width var(--nx-dur-slow) var(--nx-ease);",
  "}",
  "",
  ".nx-progress__bar--indeterminate {",
  "  animation: nx-indeterminate 1400ms var(--nx-ease) infinite;",
  "}",
  "",
  ".nx-progress__notch {",
  "  position: absolute;",
  "  top: 0;",
  "  bottom: 0;",
  "  width: 2px;",
  "  background: var(--c-bd);",
  "  opacity: 0.4;",
  "}",
  "",
  ".nx-progress__marks {",
  "  display: flex;",
  "  justify-content: space-between;",
  "  font-family: var(--nx-font-mono);",
  "  font-size: var(--nx-fs-2xs);",
  "  color: var(--c-muted);",
  "}",
  "",
  "@keyframes nx-indeterminate {",
  "  0% {",
  "    translate: -40% 0;",
  "  }",
  "  100% {",
  "    translate: 300% 0;",
  "  }",
  "}",
  "</style>",
  "",
].join("\n");

const files = {
  "reusable-components/src/components/ui/NxToggle.vue": toggle,
  "reusable-components/src/components/ui/NxSlider.vue": slider,
  "reusable-components/src/components/ui/NxProgress.vue": progress,
};

module.exports = { files };
