const checkbox = [
  "<template>",
  "  <label",
  "    class=\"nx-checkbox\"",
  "    :class=\"[classes, { 'nx-checkbox--checked': isChecked, 'nx-checkbox--disabled': disabled }]\"",
  "    :style=\"style\"",
  "  >",
  "    <input",
  "      class=\"nx-checkbox__input\"",
  "      type=\"checkbox\"",
  "      :checked=\"isChecked\"",
  "      :indeterminate=\"indeterminate\"",
  "      :disabled=\"disabled\"",
  "      :name=\"name\"",
  "      @change=\"onChange\"",
  "    />",
  "    <span class=\"nx-checkbox__box\">",
  "      <NxIcon :name=\"indeterminate ? 'minus' : 'check'\" :size=\"glyphSize\" :stroke=\"3\" />",
  "    </span>",
  "    <span class=\"nx-checkbox__body\">",
  "      <span class=\"nx-checkbox__label\"><slot>{{ label }}</slot></span>",
  "      <span v-if=\"hint\" class=\"nx-checkbox__hint\">{{ hint }}</span>",
  "    </span>",
  "  </label>",
  "</template>",
  "",
  "<script setup>",
  "import { computed } from \"vue\";",
  "import NxIcon from \"./NxIcon.vue\";",
  "import { useBox, useVisuals } from \"@/composables/useVisuals\";",
  "import { visualProps } from \"@/config/visualProps\";",
  "",
  "const GLYPH_SIZES = { xs: 10, sm: 11, md: 13, lg: 15, xl: 18 };",
  "",
  "const props = defineProps({",
  "  ...visualProps,",
  "  modelValue: { type: [Boolean, Array], default: false },",
  "  value: { type: [String, Number], default: null },",
  "  label: { type: String, default: \"Checkbox\" },",
  "  hint: { type: String, default: \"\" },",
  "  name: { type: String, default: \"\" },",
  "  indeterminate: { type: Boolean, default: false },",
  "  disabled: { type: Boolean, default: false },",
  "});",
  "",
  "const emit = defineEmits([\"update:modelValue\", \"change\"]);",
  "",
  "const isArrayMode = computed(() => Array.isArray(props.modelValue));",
  "",
  "const isChecked = computed(() => {",
  "  if (isArrayMode.value) return props.modelValue.includes(props.value);",
  "  return Boolean(props.modelValue);",
  "});",
  "",
  "const { vars, classes } = useVisuals(props, {",
  "  base: {",
  "    bg: \"var(--nx-surface-2)\",",
  "    fg: \"var(--nx-ink)\",",
  "    border: \"var(--nx-ink)\",",
  "    accent: \"var(--nx-accent)\",",
  "  },",
  "});",
  "",
  "const box = useBox(props);",
  "",
  "const style = computed(() => ({ ...vars.value, ...box.value }));",
  "const glyphSize = computed(() => GLYPH_SIZES[props.size] || GLYPH_SIZES.md);",
  "",
  "function onChange() {",
  "  if (isArrayMode.value) {",
  "    const next = props.modelValue.slice();",
  "    const index = next.indexOf(props.value);",
  "    if (index === -1) next.push(props.value);",
  "    else next.splice(index, 1);",
  "    emit(\"update:modelValue\", next);",
  "    emit(\"change\", next);",
  "    return;",
  "  }",
  "  emit(\"update:modelValue\", !props.modelValue);",
  "  emit(\"change\", !props.modelValue);",
  "}",
  "</script>",
  "",
  "<style scoped>",
  ".nx-checkbox {",
  "  display: inline-flex;",
  "  align-items: flex-start;",
  "  gap: var(--nx-ctl-gap);",
  "  padding: var(--c-py, 4px) var(--c-px, 4px);",
  "  color: var(--c-fg);",
  "  cursor: pointer;",
  "  border-radius: var(--c-radius, var(--nx-ctl-radius));",
  "}",
  "",
  ".nx-checkbox__input {",
  "  position: absolute;",
  "  width: 1px;",
  "  height: 1px;",
  "  opacity: 0;",
  "  pointer-events: none;",
  "}",
  "",
  ".nx-checkbox__box {",
  "  display: grid;",
  "  place-items: center;",
  "  width: var(--c-box, 1.25em);",
  "  height: var(--c-box, 1.25em);",
  "  flex: none;",
  "  margin-top: 0.1em;",
  "  font-size: var(--c-font-size, var(--nx-ctl-font));",
  "  color: transparent;",
  "  background-color: var(--c-bg);",
  "  border: var(--c-bd-w, var(--nx-ctl-border)) var(--c-bd-style, solid) var(--c-bd);",
  "  border-radius: var(--c-radius, var(--nx-ctl-radius));",
  "  transition: background-color var(--nx-dur) var(--nx-ease), color var(--nx-dur) var(--nx-ease);",
  "  filter: var(--c-filter);",
  "  box-shadow: var(--c-shadow);",
  "}",
  "",
  ".nx-checkbox--checked .nx-checkbox__box {",
  "  background-color: var(--c-accent);",
  "  color: var(--nx-on-accent);",
  "}",
  "",
  ".nx-checkbox__input:focus-visible + .nx-checkbox__box {",
  "  box-shadow: 0 0 0 3px var(--c-accent);",
  "}",
  "",
  ".nx-checkbox__body {",
  "  display: flex;",
  "  flex-direction: column;",
  "  gap: 2px;",
  "  min-width: 0;",
  "}",
  "",
  ".nx-checkbox__label {",
  "  font-size: var(--c-font-size, var(--nx-ctl-font));",
  "  font-weight: var(--c-weight, 600);",
  "  line-height: 1.35;",
  "}",
  "",
  ".nx-checkbox__hint {",
  "  font-size: var(--nx-fs-xs);",
  "  color: var(--c-muted);",
  "}",
  "",
  ".nx-checkbox--disabled {",
  "  opacity: 0.55;",
  "  cursor: not-allowed;",
  "}",
  "</style>",
  "",
].join("\n");

const spinner = [
  "<template>",
  "  <div",
  "    class=\"nx-spinner\"",
  "    :class=\"[classes, `nx-spinner--${variant}`]\"",
  "    :style=\"style\"",
  "    role=\"status\"",
  "    :aria-label=\"label || 'Loading'\"",
  "  >",
  "    <span class=\"nx-spinner__stage\">",
  "      <span v-if=\"variant === 'ring'\" class=\"nx-spinner__ring\" />",
  "      <template v-else-if=\"variant === 'dots'\">",
  "        <span",
  "          v-for=\"dot in 3\"",
  "          :key=\"dot\"",
  "          class=\"nx-spinner__dot\"",
  "          :style=\"{ animationDelay: (dot - 1) * 140 + 'ms' }\"",
  "        />",
  "      </template>",
  "      <template v-else-if=\"variant === 'bars'\">",
  "        <span",
  "          v-for=\"bar in 4\"",
  "          :key=\"bar\"",
  "          class=\"nx-spinner__bar\"",
  "          :style=\"{ animationDelay: (bar - 1) * 120 + 'ms' }\"",
  "        />",
  "      </template>",
  "      <span v-else class=\"nx-spinner__pulse\" />",
  "    </span>",
  "",
  "    <span v-if=\"label && showLabel\" class=\"nx-spinner__label\">{{ label }}</span>",
  "  </div>",
  "</template>",
  "",
  "<script setup>",
  "import { computed } from \"vue\";",
  "import { useBox, useVisuals } from \"@/composables/useVisuals\";",
  "import { visualProps } from \"@/config/visualProps\";",
  "",
  "const SIZE_SCALE = { xs: 14, sm: 18, md: 24, lg: 34, xl: 46 };",
  "",
  "const props = defineProps({",
  "  ...visualProps,",
  "  variant: { type: String, default: \"ring\" },",
  "  label: { type: String, default: \"\" },",
  "  showLabel: { type: Boolean, default: true },",
  "  thickness: { type: Number, default: 3 },",
  "  speed: { type: Number, default: 800 },",
  "});",
  "",
  "const { vars, classes } = useVisuals(props, {",
  "  base: {",
  "    bg: \"transparent\",",
  "    fg: \"var(--nx-ink)\",",
  "    border: \"var(--nx-accent)\",",
  "    accent: \"var(--nx-accent)\",",
  "  },",
  "});",
  "",
  "const box = useBox(props);",
  "",
  "const scale = computed(() => SIZE_SCALE[props.size] || SIZE_SCALE.md);",
  "",
  "const style = computed(() => ({",
  "  ...vars.value,",
  "  ...box.value,",
  "  \"--c-spin-size\": `${scale.value}px`,",
  "  \"--c-spin-width\": `${props.thickness}px`,",
  "  \"--c-spin-dur\": `${props.speed}ms`,",
  "}));",
  "</script>",
  "",
  "<style scoped>",
  ".nx-spinner {",
  "  display: inline-flex;",
  "  align-items: center;",
  "  gap: var(--nx-ctl-gap);",
  "  color: var(--c-fg);",
  "  filter: var(--c-filter);",
  "  transform: var(--c-transform);",
  "  opacity: var(--c-opacity);",
  "  mix-blend-mode: var(--c-blend);",
  "}",
  "",
  ".nx-spinner__stage {",
  "  display: inline-flex;",
  "  align-items: center;",
  "  justify-content: center;",
  "  gap: 3px;",
  "  width: var(--c-spin-size);",
  "  height: var(--c-spin-size);",
  "}",
  "",
  ".nx-spinner__ring {",
  "  width: 100%;",
  "  height: 100%;",
  "  border: var(--c-spin-width) solid var(--c-bd);",
  "  border-top-color: transparent;",
  "  border-radius: var(--c-radius, 999px);",
  "  animation: nx-spin var(--c-spin-dur) linear infinite;",
  "  box-shadow: var(--c-shadow);",
  "}",
  "",
  ".nx-spinner__dot {",
  "  width: calc(var(--c-spin-size) * 0.28);",
  "  height: calc(var(--c-spin-size) * 0.28);",
  "  background: var(--c-accent);",
  "  border: 2px solid var(--c-bd);",
  "  border-radius: 999px;",
  "  animation: nx-bounce-dot var(--c-spin-dur) var(--nx-ease) infinite;",
  "}",
  "",
  ".nx-spinner__bar {",
  "  width: calc(var(--c-spin-size) * 0.16);",
  "  height: 100%;",
  "  background: var(--c-accent);",
  "  border: 2px solid var(--c-bd);",
  "  animation: nx-stretch var(--c-spin-dur) var(--nx-ease) infinite;",
  "}",
  "",
  ".nx-spinner__pulse {",
  "  width: 100%;",
  "  height: 100%;",
  "  background: var(--c-accent);",
  "  border: var(--c-spin-width) solid var(--c-bd);",
  "  animation: nx-pulse var(--c-spin-dur) var(--nx-ease) infinite;",
  "}",
  "",
  ".nx-spinner__label {",
  "  font-size: var(--nx-fs-xs);",
  "  font-weight: 700;",
  "  letter-spacing: 0.04em;",
  "  text-transform: uppercase;",
  "}",
  "",
  "@keyframes nx-spin {",
  "  to {",
  "    rotate: 360deg;",
  "  }",
  "}",
  "",
  "@keyframes nx-bounce-dot {",
  "  0%,",
  "  100% {",
  "    translate: 0 0;",
  "  }",
  "  50% {",
  "    translate: 0 -30%;",
  "  }",
  "}",
  "",
  "@keyframes nx-stretch {",
  "  0%,",
  "  100% {",
  "    scale: 1 0.5;",
  "  }",
  "  50% {",
  "    scale: 1 1;",
  "  }",
  "}",
  "</style>",
  "",
].join("\n");

const avatar = [
  "<template>",
  "  <span",
  "    class=\"nx-avatar\"",
  "    :class=\"[classes, `nx-avatar--${shape}`, `nx-avatar--${sizeLabel}`]\"",
  "    :style=\"style\"",
  "  >",
  "    <img",
  "      v-if=\"src && !failed\"",
  "      class=\"nx-avatar__image\"",
  "      :src=\"src\"",
  "      :alt=\"altText\"",
  "      @error=\"failed = true\"",
  "    />",
  "    <span v-else class=\"nx-avatar__initials\">{{ resolvedInitials }}</span>",
  "",
  "    <span v-if=\"status !== 'none'\" class=\"nx-avatar__status\" :class=\"`nx-avatar__status--${status}`\" />",
  "    <span v-if=\"$slots.badge\" class=\"nx-avatar__badge\"><slot name=\"badge\" /></span>",
  "  </span>",
  "</template>",
  "",
  "<script setup>",
  "import { computed, ref } from \"vue\";",
  "import { useBox, useVisuals } from \"@/composables/useVisuals\";",
  "import { visualProps } from \"@/config/visualProps\";",
  "",
  "const SIZE_SCALE = { xs: 28, sm: 36, md: 46, lg: 60, xl: 78 };",
  "",
  "const props = defineProps({",
  "  ...visualProps,",
  "  src: { type: String, default: \"\" },",
  "  name: { type: String, default: \"\" },",
  "  initials: { type: String, default: \"\" },",
  "  shape: { type: String, default: \"square\" },",
  "  status: { type: String, default: \"none\" },",
  "  ring: { type: Boolean, default: false },",
  "});",
  "",
  "const failed = ref(false);",
  "",
  "const { vars, classes } = useVisuals(props, {",
  "  base: {",
  "    bg: \"var(--nx-surface-3)\",",
  "    fg: \"var(--nx-ink)\",",
  "    border: \"var(--nx-ink)\",",
  "    accent: \"var(--nx-accent)\",",
  "  },",
  "});",
  "",
  "const box = useBox(props);",
  "",
  "const sizeLabel = computed(() => (SIZE_SCALE[props.size] ? props.size : \"md\"));",
  "",
  "const resolvedInitials = computed(() => {",
  "  if (props.initials) return props.initials.slice(0, 2).toUpperCase();",
  "  const parts = String(props.name || \"\").trim().split(/\\s+/).filter(Boolean);",
  "  if (!parts.length) return \"?\";",
  "  const first = parts[0].charAt(0);",
  "  const last = parts.length > 1 ? parts[parts.length - 1].charAt(0) : \"\";",
  "  return `${first}${last}`.toUpperCase();",
  "});",
  "",
  "const altText = computed(() => props.name || props.alt || \"Avatar\");",
  "",
  "const style = computed(() => ({",
  "  ...vars.value,",
  "  ...box.value,",
  "  \"--c-avatar\": `${SIZE_SCALE[sizeLabel.value]}px`,",
  "  \"--c-avatar-ring\": props.ring ? `0 0 0 3px ${vars.value[\"--c-accent\"]}` : \"none\",",
  "}));",
  "</script>",
  "",
  "<style scoped>",
  ".nx-avatar {",
  "  position: relative;",
  "  display: inline-grid;",
  "  place-items: center;",
  "  flex: none;",
  "  width: var(--c-avatar);",
  "  height: var(--c-avatar);",
  "  color: var(--c-fg);",
  "  background-color: var(--c-bg);",
  "  border: var(--c-bd-w, var(--nx-ctl-border)) var(--c-bd-style, solid) var(--c-bd);",
  "  border-radius: var(--c-radius, 0);",
  "  box-shadow: var(--c-avatar-ring), var(--c-shadow);",
  "  filter: var(--c-filter);",
  "  transform: var(--c-transform);",
  "  opacity: var(--c-opacity);",
  "  overflow: visible;",
  "}",
  "",
  ".nx-avatar--round {",
  "  border-radius: var(--c-radius, 999px);",
  "}",
  "",
  ".nx-avatar--squircle {",
  "  border-radius: var(--c-radius, 34%);",
  "}",
  "",
  ".nx-avatar__image {",
  "  width: 100%;",
  "  height: 100%;",
  "  object-fit: cover;",
  "  border-radius: inherit;",
  "}",
  "",
  ".nx-avatar__initials {",
  "  font-size: calc(var(--c-avatar) * 0.38);",
  "  font-weight: 800;",
  "  letter-spacing: 0.02em;",
  "  text-transform: uppercase;",
  "}",
  "",
  ".nx-avatar__status {",
  "  position: absolute;",
  "  right: -3px;",
  "  bottom: -3px;",
  "  width: calc(var(--c-avatar) * 0.28);",
  "  height: calc(var(--c-avatar) * 0.28);",
  "  min-width: 10px;",
  "  min-height: 10px;",
  "  border: 2px solid var(--c-bd);",
  "  border-radius: 999px;",
  "  background: var(--nx-muted);",
  "}",
  "",
  ".nx-avatar__status--online {",
  "  background: var(--nx-success);",
  "}",
  "",
  ".nx-avatar__status--busy {",
  "  background: var(--nx-danger);",
  "}",
  "",
  ".nx-avatar__status--away {",
  "  background: var(--nx-warn);",
  "}",
  "",
  ".nx-avatar__badge {",
  "  position: absolute;",
  "  top: -6px;",
  "  left: -6px;",
  "}",
  "</style>",
  "",
].join("\n");

const alert = [
  "<template>",
  "  <div class=\"nx-alert\" :class=\"[classes, `nx-alert--${tone}`]\" :style=\"style\" role=\"alert\">",
  "    <span v-if=\"showIcon\" class=\"nx-alert__icon\">",
  "      <NxIcon :name=\"resolvedIcon\" :size=\"glyphSize\" />",
  "    </span>",
  "",
  "    <div class=\"nx-alert__body\">",
  "      <p v-if=\"title\" class=\"nx-alert__title\">{{ title }}</p>",
  "      <div class=\"nx-alert__message\"><slot>{{ message }}</slot></div>",
  "    </div>",
  "",
  "    <div v-if=\"$slots.actions\" class=\"nx-alert__actions\"><slot name=\"actions\" /></div>",
  "",
  "    <button",
  "      v-if=\"dismissible\"",
  "      class=\"nx-alert__close\"",
  "      type=\"button\"",
  "      aria-label=\"Dismiss\"",
  "      @click=\"$emit('dismiss')\"",
  "    >",
  "      <NxIcon name=\"close\" :size=\"glyphSize - 2\" />",
  "    </button>",
  "  </div>",
  "</template>",
  "",
  "<script setup>",
  "import { computed } from \"vue\";",
  "import NxIcon from \"./NxIcon.vue\";",
  "import { useBox, useVisuals } from \"@/composables/useVisuals\";",
  "import { visualProps } from \"@/config/visualProps\";",
  "",
  "const TONES = {",
  "  neutral: { bg: \"var(--nx-surface-3)\", fg: \"var(--nx-ink)\", border: \"var(--nx-ink)\", icon: \"info\" },",
  "  info: { bg: \"var(--nx-info)\", fg: \"var(--nx-ink)\", border: \"var(--nx-ink)\", icon: \"info\" },",
  "  success: { bg: \"var(--nx-success)\", fg: \"var(--nx-ink)\", border: \"var(--nx-ink)\", icon: \"check\" },",
  "  warn: { bg: \"var(--nx-warn)\", fg: \"var(--nx-ink)\", border: \"var(--nx-ink)\", icon: \"warning\" },",
  "  danger: { bg: \"var(--nx-danger)\", fg: \"var(--nx-on-accent)\", border: \"var(--nx-ink)\", icon: \"alert\" },",
  "};",
  "",
  "const GLYPH_SIZES = { xs: 14, sm: 16, md: 18, lg: 20, xl: 24 };",
  "",
  "const props = defineProps({",
  "  ...visualProps,",
  "  tone: { type: String, default: \"info\" },",
  "  title: { type: String, default: \"\" },",
  "  message: { type: String, default: \"\" },",
  "  icon: { type: String, default: \"\" },",
  "  showIcon: { type: Boolean, default: true },",
  "  dismissible: { type: Boolean, default: false },",
  "  striped: { type: Boolean, default: false },",
  "});",
  "",
  "defineEmits([\"dismiss\"]);",
  "",
  "const { vars, classes } = useVisuals(props, {",
  "  base: () => TONES[props.tone] || TONES.info,",
  "});",
  "",
  "const box = useBox(props);",
  "",
  "const resolvedIcon = computed(() => props.icon || (TONES[props.tone] || TONES.info).icon);",
  "const glyphSize = computed(() => GLYPH_SIZES[props.size] || GLYPH_SIZES.md);",
  "",
  "const style = computed(() => ({ ...vars.value, ...box.value }));",
  "</script>",
  "",
  "<style scoped>",
  ".nx-alert {",
  "  display: flex;",
  "  align-items: flex-start;",
  "  gap: var(--nx-ctl-gap);",
  "  padding: var(--c-py, var(--nx-ctl-pad-y)) var(--c-px, var(--nx-ctl-pad-x));",
  "  color: var(--c-fg);",
  "  background-color: var(--c-bg);",
  "  border: var(--c-bd-w, var(--nx-ctl-border)) var(--c-bd-style, solid) var(--c-bd);",
  "  border-radius: var(--c-radius, var(--nx-ctl-radius));",
  "  backdrop-filter: var(--c-backdrop, none);",
  "  font-size: var(--c-font-size, var(--nx-ctl-font));",
  "  line-height: var(--c-lh, 1.5);",
  "}",
  "",
  ".nx-alert__icon {",
  "  display: grid;",
  "  place-items: center;",
  "  flex: none;",
  "  margin-top: 1px;",
  "}",
  "",
  ".nx-alert__body {",
  "  flex: 1 1 auto;",
  "  min-width: 0;",
  "}",
  "",
  ".nx-alert__title {",
  "  margin: 0 0 2px;",
  "  font-size: var(--c-font-size, var(--nx-ctl-font));",
  "  font-weight: 800;",
  "  letter-spacing: 0.01em;",
  "}",
  "",
  ".nx-alert__message {",
  "  opacity: 0.92;",
  "}",
  "",
  ".nx-alert__actions {",
  "  display: inline-flex;",
  "  align-items: center;",
  "  gap: var(--nx-sp-3);",
  "  flex: none;",
  "}",
  "",
  ".nx-alert__close {",
  "  display: grid;",
  "  place-items: center;",
  "  flex: none;",
  "  padding: 2px;",
  "  color: inherit;",
  "  background: none;",
  "  border: 0;",
  "  cursor: pointer;",
  "  opacity: 0.75;",
  "}",
  "",
  ".nx-alert__close:hover {",
  "  opacity: 1;",
  "}",
  "</style>",
  "",
].join("\n");

const files = {
  "reusable-components/src/components/ui/NxCheckbox.vue": checkbox,
  "reusable-components/src/components/ui/NxSpinner.vue": spinner,
  "reusable-components/src/components/ui/NxAvatar.vue": avatar,
  "reusable-components/src/components/ui/NxAlert.vue": alert,
};

module.exports = { files };
